"""Badge rendering: shields.io static badges in the Atlas brand palette.

flat-square because the whole estate is square corners and hard edges;
labelColor pinned to the site background so a badged README on GitHub's
white or dark theme still reads as a strip of the site itself.
"""

from __future__ import annotations

from .concepts import CATEGORIES, CONCEPTS_BY_ID, sort_key

START_MARKER = "<!-- ATLAS_CONCEPT_BADGES:START -->"
END_MARKER = "<!-- ATLAS_CONCEPT_BADGES:END -->"
GENERATED_NOTE = (
    "<!-- generated by atlas-badges; override with .atlas-concepts.yml, "
    "don't hand-edit inside these markers -->"
)

LABEL_COLOR = "0a0a0f"


def _escape(text: str) -> str:
    """shields.io static-badge escaping: literal dash doubles, literal
    underscore doubles, space becomes underscore. A slash is percent-encoded
    so the whole badge spec stays a single URL path segment."""
    return (
        text.replace("-", "--")
        .replace("_", "__")
        .replace(" ", "_")
        .replace("/", "%2F")
    )


def badge_url(label: str, message: str, color: str) -> str:
    return (
        "https://img.shields.io/badge/"
        f"{_escape(label)}-{_escape(message)}-{color}"
        f"?style=flat-square&labelColor={LABEL_COLOR}"
    )


def badge_markdown(concept_id: str) -> str:
    concept = CONCEPTS_BY_ID[concept_id]
    category = CATEGORIES[concept.category]
    url = badge_url(category["label"], concept.name, category["color"])
    alt = f"{category['label']}: {concept.name}"
    return f"![{alt}]({url})"


def render_block(concept_ids: set[str]) -> str:
    """The full marker-delimited block. Deterministic ordering keeps
    re-runs byte-identical, which is what makes `apply` idempotent."""
    ordered = sorted(
        (CONCEPTS_BY_ID[cid] for cid in concept_ids if cid in CONCEPTS_BY_ID),
        key=sort_key,
    )
    lines = [START_MARKER, GENERATED_NOTE]
    if ordered:
        lines.append("\n".join(badge_markdown(c.id) for c in ordered))
    else:
        lines.append("<!-- no concepts detected or forced; scan again after changes -->")
    lines.append(END_MARKER)
    return "\n".join(lines)
